### PR TITLE
Fix tests with non-ASCII file names

### PR DESCRIPTION
**Pull request by timgraham**
As per https://docs.djangoproject.com/en/dev/ref/unicode/#files

### CODE REVIEW

**Comment by timgraham** [comment]
@rohany, I updated the Dockerfile based on https://daten-und-bass.io/blog/fixing-missing-locale-setting-in-ubuntu-docker-image/. Could we try that?

**Comment by rohany** [comment]
@jordanlewis can you do the build? The repo is cockroachdb/cockroach-django-builder

**Comment by rafiss** [comment]
It seems like the change caused a few unexpected successes to happen. Do we need to update the list of expected test results?

```
test_trunc_hour_func (db_functions.datetime.test_extract_trunc.DateFunctionTests) ... unexpected success
test_trunc_minute_func (db_functions.datetime.test_extract_trunc.DateFunctionTests) ... unexpected success
test_trunc_second_func (db_functions.datetime.test_extract_trunc.DateFunctionTests) ... unexpected success
test_extract_func (db_functions.datetime.test_extract_trunc.DateFunctionWithTimeZoneTests) ... unexpected success
test_extract_hour_func (db_functions.datetime.test_extract_trunc.DateFunctionWithTimeZoneTests) ... unexpected success
test_trunc_time_func (db_functions.datetime.test_extract_trunc.DateFunctionWithTimeZoneTests) ... unexpected success
test_mixed_comparisons1 (expressions.tests.FTimeDeltaTests) ... unexpected success
test_slice_subquery_and_query (queries.tests.SubqueryTests) ... unexpected success
```

**Comment by timgraham** [comment]
Those issues are unrelated to this PR. Some unexpected successes are expected (https://github.com/cockroachdb/cockroach-django/issues/48 and https://github.com/cockroachdb/cockroach-django/blob/df19009cdf6447529f29219520104034329a8bac/cockroach/django/creation.py#L153-L155
) ... I believe `test_mixed_comparisons1` started passing after daylight saving time ended last Sunday night (which may be a bug in cockroachdb).

This PR is still awaiting the changes in the Dockerfile to be pushed to cockroach-django-builder (unless you've done that and we just need to retrigger a build).

**Comment by rafiss** [comment]
Ah ok, got it. I'm working on getting access to our Docker Hub org.

**Pull request merged**
