### PR TITLE
Add more apps to CI tests

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by timgraham** [comment]
This isn't ready for a merge yet as it looks like the tests are too much for teamcity.  It looks like cockroachdb is shutting down after "FATAL: disk stall detected: unable to sync log files within 30s".

**Comment by timgraham** [comment]
@rohany, maybe you can help debug why cockroachdb terminates? I've seen an issue on my machine where when running cockroach with `--store=type=mem`, memory isn't reclaimed until the server shuts down. Possibly this could be related? I don't think it's a particular Django app that's triggering this but merely running a lot of tests in one build.

**Comment by rohany** [comment]
Does this repro when you don’t use that flag? I guess it would slow tests down a good amount. We have some commands to help speed up tests suites which I can try to hook in tomorrow.

**Comment by timgraham** [comment]
Sorry if I sidetracked things. That issue isn't actually a problem for me as I have plenty of memory... and the teamcity build isn't using `--store=type=mem`. Thanks for looking at this... not particularly urgent until we want to run as many tests as we can.

**Comment by timgraham** [comment]
I added a commit to use a branch of Django which includes https://github.com/timgraham/django/commit/a204f21b68e18388098ecaaa982b422c96109de3. This speeds up the tests tremendously and allows the build to finish, however, it creates some new `TransactionManagementError` test failures which I haven't investigated.

**Pull request merged**
