### PR TITLE
Adds flake8 and isort tests to teamcity

### PR DESCRIPTION
**Pull request by rohany**
This PR adds flake8 and isort tests as steps in teamcity.

### CODE REVIEW

**Comment by rohany** [comment]
@timgraham are the flake8 errors in the output here valid? I thought one of your earlier PR's should have fixed the flake8 errors.

**Comment by timgraham** [comment]
The build seems to be failing with an invalid pointer error from docker-credential-helpers.

**Comment by rohany** [comment]
I’m not sure about that error(it’s reoccurring consistently), but it doesn’t stop the build — look further down the output at the flake8 errors

**Comment by timgraham** [comment]
Need to cd into the `cockroach-django` directory. The errors are coming from other files like /docker_root/home/agent/.local/lib/python3.6/site-packages/entrypoints.py

**Comment by rohany** [comment]
That makes sense. Thanks for the guidance, I've never used these tools before.

**Comment by rohany** [comment]
I'm going to merge this, please rebase your PR's onto here to get these checks to pass.

**Pull request merged**
