### PR TITLE
Allow marking tests as expected failure

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by rohany** [comment]
We’re also maintaining a blacklist of tests marked with issues. @jordanlewis should we just try and keep the roach test blacklist up to date with this list?

**Comment by jordanlewis** [comment]
I guess so, although it seems unfortunate that there would be 2 sources of truth... any ideas for how to keep them in sync more efficiently than by hand?

**Comment by timgraham** [comment]
I'm not sure of the purpose of the second list but it might be obsoleted by this (i.e. how would you run the tests without this code running)?

**Comment by rohany** [comment]
Our blacklist is to aggregate issues across multiple drivers / ORMs and see what common features are missing. Does this change here automatically skip these tests? 

It seems like for our purposes of data collection we could just copy this blacklist.

**Comment by timgraham** [comment]
Python's `unittest.expectedFailure` runs a test and "passes" with "expected failure" if the test fails. If the test passes, it will report a "failure" of "unexpected success." So if cockroachdb fixes an issue that allows these tests to work, the test suite will notify us and we can remove the tests from this list.

**Comment by rohany** [comment]
Ok, that sounds good. I think we should merge this and use the blacklist that gets created here as a basis for a blacklist in the roachtest.

**Pull request merged**
