### PR TITLE
Ignore partial indexes and PostgreSQL opclasses

### PR DESCRIPTION
**Pull request by timgraham**
The `indexes` tests now pass.

### CODE REVIEW

**Comment by rohany** [comment]
I'm not sure if this is related to this change or not, but when running the postgres tests, i noticed that django would generate index statements like
```
create index ... using btree (fillfactor=80)
```

We don't support the extra arguments (fillfactor...). Is there a way to notify django about that?

**Comment by timgraham** [comment]
You could try removing `%(extra)s` from the `sql_create_index` string but that's rather blunt and I'm not certain it wouldn't drop something useful that cockroach does support.

https://github.com/django/django/blob/d232fd76a85870daf345fd8f8d617fe7802ae194/django/contrib/postgres/indexes.py#L26-L29

In the long run, it might be better to develop your own `contrib.cockroachdb` customized version of `django.contrib.postgres` with the subset of things that cockroach supports.

**Comment by timgraham** [comment]
Is this fine to merge after I rebase it, Rohan?

**Comment by rohany** [comment]
Yeah go ahead, I didn't have any more comments after your message. I think i forgot to give it a thumbs up or something.

**Pull request merged**
